config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  root "users#index"
  resources :products
  devise_for :users
  post "checkout/create", to: "checkout#create"
  get "checkout/success", to: "checkout#success"
  get "checkout/failure", to: "checkout#failure"
  # resources :webhooks, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  validates :name, :discription, :price, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  has_many :products
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :assign_default_role

  def assign_default_role
    self.add_role(:buyer) if self.roles.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

	$product_qty = nil
	$product_id = nil
	def create
		
		product = Product.find(params[:pid])
		$product_id = product.id
		$product_qty = params[:qty]
		total = product.price * $product_qty.to_i
		max = 999999
		if total<max
		@session = Stripe::Checkout::Session.create({
			payment_method_types: ['card'],
			line_items: [{
				name: product.name,
				amount: product.price*100,
				currency: "inr",
				quantity: params[:qty] 
			}],
			mode: 'payment',
			
			success_url: checkout_success_url, 

			cancel_url: checkout_failure_url,

		})
		
		
		redirect_to @session.url
		else
            redirect_to checkout_failure_url
        end
	
		end
		
		def success
				# debugger
			@product = Product.find_by(id: $product_id)
			if @product.present?
				@product.quantity -= $product_qty.to_i
				@product.update(quantity:@product.quantity)
        		PaymentInformationMailer.create_invoice(@product,$product_qty,current_user.email).deliver_now #if response.request.url == "http://localhost:3000/success"
        		$product_qty = nil
        		$product_id = nil
    		end
		
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @products = Product.all
  end
 
  def show
    @product = Product.find(params[:id])
  end
  
  def new
    @product = Product.new
  end
 
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to products_path
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    if @product.destroy
      redirect_to @product, notice: "Product deleted."
    end

  end

  private
    
    def product_params
      params.require(:product).permit(:id, :name, :discription, :quantity, :price, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
      # UserMailer.example(User.new(email: 'test@gmail.com')).deliver
      @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/checkout/create.js.erb
var stripe = Stripe("pk_test_51LPjtRSACyU2YO2O2sgBofdffs8Xd1S7EWGyOJ4GGnGwlpgn9OtqFVE1OVujIdVN2vsJGNz5B1NcD22APbUMkShQ00pL0isbQT");
  
  stripe.redirectToCheckout({
    // Make the id field from the Checkout Session creation API response
    // available to this file, so you can provide it as argument here
    // instead of the {{CHECKOUT_SESSION_ID}} placeholder.
    
    sessionId: '<%= @session.id %>',
    
    
  }).then(function (result) {
    console.log(result.error.message);
  });

app/views/checkout/failure.html.erb
<h3>Payment Failed !</h3>
<p>please try again..</p>
<%= link_to "Back", root_path%>

app/views/checkout/success.html.erb
<h4>Thank you for purchase. </h4>
<%= link_to 'Back', root_path%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href=<%= root_path %>>Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0" align= "left">
        <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to "Hi, #{current_user.email}", edit_user_registration_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
    </li>
  <% else %>
    <li class="nav-item">
      <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
    </li>
  <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Shoping</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <script src="https://js.stripe.com/v3/"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'layouts/navbar' %>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>

</html>

app/views/products/_form.html.erb
<fieldset>
  <%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
      <% product.errors.each do |error| %>
      <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
<div class="container mt-3 bg-success text-white">
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :discription %>
    <%= form.text_field :discription %>
  </div>

  <div class="field">
    <%= form.hidden_field :quantity, value:1000 %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions" align="center">
    <button type="button" class="btn btn-primary"><%= form.submit %></button>
  </div>
  </div>
  <% end %>
</fieldset>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<fieldset>
  <p id="notice"><%= notice %></p>

  <h1>Products</h1>

  <table class="table">
    <thead class="table-primary"> 
      <tr>
        <th>Name</th>
        <th>Discription</th>

        <th>Price</th>

        <th><% if current_user.has_role? :seller %></th>

        <th colspan="3"></th>
        <th><%end%></th>
      </tr>
    </thead>

    <tbody class="table-success">
      <% @products.each do |product| %>
      <tr>
        <td><h3 class="badge rounded-pill bg-success"><%= product.name %></td></h3>
        <td><%= product.discription %></td>
        <td><%= product.price %></td>
        <td ><%= button_to 'Show', product, method: :get %></td>
        <% if current_user.has_role? :seller %>
        <td><%= button_to 'Edit', edit_product_path(product), method: :get %></td>
        <td><%= button_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
        <td></td><td></td>
        <%end%>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if current_user.has_role? :seller %>
    <p class="btn btn-warning"><%= link_to 'New Product', new_product_path, method: :get %></p>
  <%end%>
  <br>
  <p class="btn btn-danger"><%= link_to "Back", root_path%></p>
</fieldset>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<button type="button" class="btn btn-info"><%= link_to 'Back', products_path %></button>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Discription:</strong>
  <%= @product.discription %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>User:</strong>
  <%= @product.user_id %>
</p>
<% if user_signed_in? %>
  <%= form_tag checkout_create_path,  method: :post, data: { turbo: false } do %>
  <input type="hidden" name="pid" value="<%= @product.id%>">
  <input type="text" name="qty">
  <%= submit_tag "Buy Now", data: { disable_with: "Hold please..." }, class: "btn btn-dark" %>
    <% end %>
<% end %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/users/index.html.erb
<p class="navbar-text float-right">
  <% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= button_to "All Products", products_path, method: :get %>
  
  <% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>